### PR TITLE
ADDED package.json

### PR DESCRIPTION
**Pull request by stefanocudini**
support for npm packages..

@jmoraleda after you need to do:

```
npm publish .
```

I have to be able to use your library through NPM

### CODE REVIEW

**Comment by jmoraleda** [comment]
@stefanocudini Merged!
You can do the publish yourself ;)

**Comment by stefanocudini** [comment]
If I do the publish... I become the owner of the npm package, may be best way for future updates that you publish it with your npm account

**Comment by brickpop** [comment]
OK, I just made it
You can check it out on https://www.npmjs.com/package/jbpivot

Hope it helps!

**Comment by jbaylina** [comment]
Stephano and jordi, I believe that it should be a bower package more than a npm package.

**Comment by stefanocudini** [comment]
@jbaylina yes! I agree!

**Comment by stefanocudini** [comment]
@deneb1

**Pull request merged**
